project_id = "lfipxpoypivbiraavtkw"

[functions.cleanup-sold-listings]
verify_jwt = false

[functions.farming-alerts]
verify_jwt = false

[functions.ai-market-prices]
verify_jwt = false

[functions.ai-market-insights]
verify_jwt = false

[functions.weather-forecast]
verify_jwt = false

[functions.farming-assistant]
verify_jwt = false

[functions.health-diagnosis]
verify_jwt = false

[functions.crop-planner]
verify_jwt = false

[functions.notify-expiring-listings]
verify_jwt = false
